# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BatchLookup.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'BatchLookup.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AccountPersonalShow_pb2 as AccountPersonalShow__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x42\x61tchLookup.proto\x12\x08\x66reefire\x1a\x19\x41\x63\x63ountPersonalShow.proto\"J\n\x18\x43SBatchGetAccountInfoReq\x12\x17\n\x0b\x61\x63\x63ount_ids\x18\x01 \x03(\x04\x42\x02\x10\x01\x12\x15\n\rcall_sign_src\x18\x02 \x01(\r\"R\n\x18\x43SBatchGetAccountInfoRes\x12\x36\n\x12\x61\x63\x63ount_info_basic\x18\x01 \x03(\x0b\x32\x1a.freefire.AccountInfoBasicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BatchLookup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSBATCHGETACCOUNTINFOREQ'].fields_by_name['account_ids']._loaded_options = None
  _globals['_CSBATCHGETACCOUNTINFOREQ'].fields_by_name['account_ids']._serialized_options = b'\020\001'
  _globals['_CSBATCHGETACCOUNTINFOREQ']._serialized_start=58
  _globals['_CSBATCHGETACCOUNTINFOREQ']._serialized_end=132
  _globals['_CSBATCHGETACCOUNTINFORES']._serialized_start=134
  _globals['_CSBATCHGETACCOUNTINFORES']._serialized_end=216
# @@protoc_insertion_point(module_scope)
