# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: HeroicInfo.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'HeroicInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10HeroicInfo.proto\x12\x08\x66reefire\"?\n\x12\x43SGetHeroicInfoReq\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x15\n\rneed_max_rank\x18\x02 \x01(\x08\"\xea\x01\n\x12\x43SGetHeroicInfoRes\x12\x1d\n\x11\x62r_reached_season\x18\x01 \x03(\rB\x02\x10\x01\x12\x1d\n\x11\x63s_reached_season\x18\x02 \x03(\rB\x02\x10\x01\x12&\n\x1a\x62r_reached_season_max_rank\x18\x03 \x03(\rB\x02\x10\x01\x12&\n\x1a\x63s_reached_season_max_rank\x18\x04 \x03(\rB\x02\x10\x01\x12\"\n\x16\x62r_grandmaster_seasons\x18\x05 \x03(\rB\x02\x10\x01\x12\"\n\x16\x63s_grandmaster_seasons\x18\x06 \x03(\rB\x02\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'HeroicInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSGETHEROICINFORES'].fields_by_name['br_reached_season']._loaded_options = None
  _globals['_CSGETHEROICINFORES'].fields_by_name['br_reached_season']._serialized_options = b'\020\001'
  _globals['_CSGETHEROICINFORES'].fields_by_name['cs_reached_season']._loaded_options = None
  _globals['_CSGETHEROICINFORES'].fields_by_name['cs_reached_season']._serialized_options = b'\020\001'
  _globals['_CSGETHEROICINFORES'].fields_by_name['br_reached_season_max_rank']._loaded_options = None
  _globals['_CSGETHEROICINFORES'].fields_by_name['br_reached_season_max_rank']._serialized_options = b'\020\001'
  _globals['_CSGETHEROICINFORES'].fields_by_name['cs_reached_season_max_rank']._loaded_options = None
  _globals['_CSGETHEROICINFORES'].fields_by_name['cs_reached_season_max_rank']._serialized_options = b'\020\001'
  _globals['_CSGETHEROICINFORES'].fields_by_name['br_grandmaster_seasons']._loaded_options = None
  _globals['_CSGETHEROICINFORES'].fields_by_name['br_grandmaster_seasons']._serialized_options = b'\020\001'
  _globals['_CSGETHEROICINFORES'].fields_by_name['cs_grandmaster_seasons']._loaded_options = None
  _globals['_CSGETHEROICINFORES'].fields_by_name['cs_grandmaster_seasons']._serialized_options = b'\020\001'
  _globals['_CSGETHEROICINFOREQ']._serialized_start=30
  _globals['_CSGETHEROICINFOREQ']._serialized_end=93
  _globals['_CSGETHEROICINFORES']._serialized_start=96
  _globals['_CSGETHEROICINFORES']._serialized_end=330
# @@protoc_insertion_point(module_scope)
