# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Leaderboard.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'Leaderboard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AccountPersonalShow_pb2 as AccountPersonalShow__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Leaderboard.proto\x12\x08\x66reefire\x1a\x19\x41\x63\x63ountPersonalShow.proto\"\xb8\x01\n\x10\x43SLeaderboardReq\x12\x11\n\tmain_type\x18\x01 \x01(\x05\x12\x10\n\x08sub_type\x18\x02 \x01(\x05\x12\x10\n\x08main_key\x18\x03 \x01(\x04\x12\x0f\n\x07sub_key\x18\x04 \x01(\x04\x12\x12\n\npage_index\x18\x05 \x01(\r\x12\x11\n\tpage_size\x18\x06 \x01(\r\x12\x10\n\x08get_self\x18\x07 \x01(\x08\x12\x0e\n\x06region\x18\x08 \x01(\t\x12\x13\n\x0block_region\x18\t \x01(\t\"\x8c\x01\n\x14\x41\x63\x63ountInfoWithStats\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x14\n\x0cgames_played\x18\x02 \x01(\r\x12\x0c\n\x04wins\x18\x03 \x01(\r\x12\r\n\x05kills\x18\x04 \x01(\r\x12\x16\n\x0e\x64\x65tailed_stats\x18\x05 \x01(\t\x12\x15\n\ris_cs_ranking\x18\x06 \x01(\x08\"\xd3\x01\n\x19\x41\x63\x63ountLeaderboardProfile\x12.\n\nbasic_info\x18\x01 \x01(\x0b\x32\x1a.freefire.AccountInfoBasic\x12,\n\x04stat\x18\x02 \x01(\x0b\x32\x1e.freefire.AccountInfoWithStats\x12\x0c\n\x04rank\x18\x03 \x01(\r\x12\x16\n\x0eranking_points\x18\x04 \x01(\r\x12\x1a\n\x12limited_event_info\x18\x05 \x01(\x0c\x12\x16\n\x0e\x63s_peak_points\x18\x08 \x01(\r\"d\n\x12LeaderboardProfile\x12\x10\n\x08has_data\x18\x01 \x01(\x08\x12<\n\x0f\x61\x63\x63ount_profile\x18\x02 \x01(\x0b\x32#.freefire.AccountLeaderboardProfile\"o\n\x0fLeaderboardItem\x12\x11\n\tunique_id\x18\x05 \x01(\x04\x12\r\n\x05score\x18\x02 \x01(\x01\x12-\n\x07profile\x18\x03 \x01(\x0b\x32\x1c.freefire.LeaderboardProfile\x12\x0b\n\x03pos\x18\x04 \x01(\x05\"\x7f\n\x10\x43SLeaderboardRes\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.freefire.LeaderboardItem\x12\'\n\x04self\x18\x02 \x01(\x0b\x32\x19.freefire.LeaderboardItem\x12\x18\n\x10leaderboard_size\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Leaderboard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSLEADERBOARDREQ']._serialized_start=59
  _globals['_CSLEADERBOARDREQ']._serialized_end=243
  _globals['_ACCOUNTINFOWITHSTATS']._serialized_start=246
  _globals['_ACCOUNTINFOWITHSTATS']._serialized_end=386
  _globals['_ACCOUNTLEADERBOARDPROFILE']._serialized_start=389
  _globals['_ACCOUNTLEADERBOARDPROFILE']._serialized_end=600
  _globals['_LEADERBOARDPROFILE']._serialized_start=602
  _globals['_LEADERBOARDPROFILE']._serialized_end=702
  _globals['_LEADERBOARDITEM']._serialized_start=704
  _globals['_LEADERBOARDITEM']._serialized_end=815
  _globals['_CSLEADERBOARDRES']._serialized_start=817
  _globals['_CSLEADERBOARDRES']._serialized_end=944
# @@protoc_insertion_point(module_scope)
