# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Outfit.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'Outfit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cOutfit.proto\x12\x0f\x66reefire.outfit\"+\n\x15\x43SGetAccountOutfitReq\x12\x12\n\naccount_id\x18\x01 \x01(\x04\"J\n\x0f\x41vatarSkillSlot\x12\x0f\n\x07slot_id\x18\x01 \x01(\r\x12\x10\n\x08skill_id\x18\x02 \x01(\r\x12\x14\n\x0c\x65quip_source\x18\x03 \x01(\r\"A\n\x0bItemTagInfo\x12\x0f\n\x07item_id\x18\x01 \x01(\r\x12\x11\n\tseries_id\x18\x02 \x01(\r\x12\x0e\n\x06num_id\x18\x03 \x01(\r\"\xff\x02\n\rAvatarProfile\x12\x11\n\tavatar_id\x18\x01 \x01(\r\x12\x12\n\nskin_color\x18\x03 \x01(\r\x12\x13\n\x07\x63lothes\x18\x04 \x03(\rB\x02\x10\x01\x12\x38\n\x0e\x65quiped_skills\x18\x05 \x03(\x0b\x32 .freefire.outfit.AvatarSkillSlot\x12\x13\n\x0bis_selected\x18\x06 \x01(\x08\x12\x1a\n\x12pve_primary_weapon\x18\x07 \x01(\r\x12\x1a\n\x12is_selected_awaken\x18\x08 \x01(\x08\x12\x10\n\x08\x65nd_time\x18\t \x01(\r\x12\x13\n\x0bunlock_type\x18\n \x01(\r\x12\x13\n\x0bunlock_time\x18\x0b \x01(\r\x12\x16\n\x0eis_marked_star\x18\x0c \x01(\x08\x12\"\n\x16\x63lothes_tailor_effects\x18\r \x03(\rB\x02\x10\x01\x12\x33\n\ritem_tag_info\x18\x0e \x03(\x0b\x32\x1c.freefire.outfit.ItemTagInfo\"G\n\x1f\x41\x63\x63ountCollectionCustomItemInfo\x12\x0f\n\x07item_id\x18\x01 \x01(\r\x12\x13\n\x0b\x63ustom_info\x18\x02 \x01(\t\"\xbb\x01\n\x15\x43SGetAccountOutfitRes\x12\x1f\n\x13show_selected_items\x18\x01 \x03(\rB\x02\x10\x01\x12/\n\x07profile\x18\x02 \x01(\x0b\x32\x1e.freefire.outfit.AvatarProfile\x12P\n\x16\x63ollection_custom_list\x18\x03 \x03(\x0b\x32\x30.freefire.outfit.AccountCollectionCustomItemInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Outfit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVATARPROFILE'].fields_by_name['clothes']._loaded_options = None
  _globals['_AVATARPROFILE'].fields_by_name['clothes']._serialized_options = b'\020\001'
  _globals['_AVATARPROFILE'].fields_by_name['clothes_tailor_effects']._loaded_options = None
  _globals['_AVATARPROFILE'].fields_by_name['clothes_tailor_effects']._serialized_options = b'\020\001'
  _globals['_CSGETACCOUNTOUTFITRES'].fields_by_name['show_selected_items']._loaded_options = None
  _globals['_CSGETACCOUNTOUTFITRES'].fields_by_name['show_selected_items']._serialized_options = b'\020\001'
  _globals['_CSGETACCOUNTOUTFITREQ']._serialized_start=33
  _globals['_CSGETACCOUNTOUTFITREQ']._serialized_end=76
  _globals['_AVATARSKILLSLOT']._serialized_start=78
  _globals['_AVATARSKILLSLOT']._serialized_end=152
  _globals['_ITEMTAGINFO']._serialized_start=154
  _globals['_ITEMTAGINFO']._serialized_end=219
  _globals['_AVATARPROFILE']._serialized_start=222
  _globals['_AVATARPROFILE']._serialized_end=605
  _globals['_ACCOUNTCOLLECTIONCUSTOMITEMINFO']._serialized_start=607
  _globals['_ACCOUNTCOLLECTIONCUSTOMITEMINFO']._serialized_end=678
  _globals['_CSGETACCOUNTOUTFITRES']._serialized_start=681
  _globals['_CSGETACCOUNTOUTFITRES']._serialized_end=868
# @@protoc_insertion_point(module_scope)
