# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PlayerStats.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'PlayerStats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11PlayerStats.proto\x12\x08\x66reefire\"=\n\x13\x43SGetPlayerStatsReq\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x12\n\nmatch_mode\x18\x02 \x01(\r\"\x86\x03\n\x13PlayerDetailedStats\x12\x0e\n\x06\x64\x65\x61ths\x18\x01 \x01(\r\x12\x13\n\x0btop10_times\x18\x02 \x01(\r\x12\x13\n\x0btop_n_times\x18\x03 \x01(\r\x12\x1a\n\x12\x64istance_travelled\x18\x04 \x01(\r\x12\x15\n\rsurvival_time\x18\x05 \x01(\r\x12\x0f\n\x07revives\x18\x06 \x01(\r\x12\x15\n\rhighest_kills\x18\x07 \x01(\r\x12\x0e\n\x06\x64\x61mage\x18\x08 \x01(\r\x12\x12\n\nroad_kills\x18\t \x01(\r\x12\x11\n\theadshots\x18\n \x01(\r\x12\x16\n\x0eheadshot_kills\x18\x0b \x01(\r\x12\x12\n\nknock_down\x18\x0c \x01(\r\x12\x10\n\x08pick_ups\x18\r \x01(\r\x12\x15\n\rrating_points\x18\x0e \x01(\x01\x12\x1c\n\x14rating_enabled_games\x18\x0f \x01(\r\x12\x16\n\x0egold_medal_cnt\x18\x10 \x01(\r\x12\x18\n\x10silver_medal_cnt\x18\x11 \x01(\r\"\x9c\x01\n\x1c\x41\x63\x63ountInfoWithStatsToClient\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x14\n\x0cgames_played\x18\x02 \x01(\r\x12\x0c\n\x04wins\x18\x03 \x01(\r\x12\r\n\x05kills\x18\x04 \x01(\r\x12\x35\n\x0e\x64\x65tailed_stats\x18\x05 \x01(\x0b\x32\x1d.freefire.PlayerDetailedStats\"\xc8\x01\n\x13\x43SGetPlayerStatsRes\x12:\n\nsolo_stats\x18\x01 \x01(\x0b\x32&.freefire.AccountInfoWithStatsToClient\x12\x39\n\tduo_stats\x18\x02 \x01(\x0b\x32&.freefire.AccountInfoWithStatsToClient\x12:\n\nquad_stats\x18\x03 \x01(\x0b\x32&.freefire.AccountInfoWithStatsToClientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlayerStats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSGETPLAYERSTATSREQ']._serialized_start=31
  _globals['_CSGETPLAYERSTATSREQ']._serialized_end=92
  _globals['_PLAYERDETAILEDSTATS']._serialized_start=95
  _globals['_PLAYERDETAILEDSTATS']._serialized_end=485
  _globals['_ACCOUNTINFOWITHSTATSTOCLIENT']._serialized_start=488
  _globals['_ACCOUNTINFOWITHSTATSTOCLIENT']._serialized_end=644
  _globals['_CSGETPLAYERSTATSRES']._serialized_start=647
  _globals['_CSGETPLAYERSTATSRES']._serialized_end=847
# @@protoc_insertion_point(module_scope)
