# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Search.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'Search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AccountPersonalShow_pb2 as AccountPersonalShow__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cSearch.proto\x12\x08\x66reefire\x1a\x19\x41\x63\x63ountPersonalShow.proto\"1\n\x1d\x43SFuzzySearchAccountByNameReq\x12\x10\n\x08nickname\x18\x01 \x01(\t\"F\n\x19\x41\x63\x63ountInfoBasicBundleRes\x12)\n\x05infos\x18\x01 \x03(\x0b\x32\x1a.freefire.AccountInfoBasicb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSFUZZYSEARCHACCOUNTBYNAMEREQ']._serialized_start=53
  _globals['_CSFUZZYSEARCHACCOUNTBYNAMEREQ']._serialized_end=102
  _globals['_ACCOUNTINFOBASICBUNDLERES']._serialized_start=104
  _globals['_ACCOUNTINFOBASICBUNDLERES']._serialized_end=174
# @@protoc_insertion_point(module_scope)
