# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WeaponPower.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'WeaponPower.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import AccountPersonalShow_pb2 as AccountPersonalShow__pb2
import WeaponExp_pb2 as WeaponExp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11WeaponPower.proto\x12\x08\x66reefire\x1a\x19\x41\x63\x63ountPersonalShow.proto\x1a\x0fWeaponExp.proto\";\n%CSGetAccountWeaponPowerTitleRecordReq\x12\x12\n\naccount_id\x18\x01 \x01(\x04\"\xaa\x02\n\x1aWeaponPowerTitleRecordInfo\x12\x12\n\naccount_id\x18\x01 \x01(\x04\x12\x18\n\x10leaderboard_type\x18\x02 \x01(\r\x12\x11\n\tweapon_id\x18\x03 \x01(\r\x12\x32\n\nbest_title\x18\x04 \x01(\x0b\x32\x1e.freefire.WeaponPowerTitleInfo\x12\x16\n\x0e\x63ountry_amount\x18\x05 \x01(\r\x12\x13\n\x0b\x61rea_amount\x18\x06 \x01(\r\x12\x13\n\x0b\x63ity_amount\x18\x07 \x01(\r\x12\x11\n\tseason_id\x18\x08 \x01(\r\x12\x14\n\x0cweapon_power\x18\t \x01(\r\x12\x17\n\x0fweapon_headshot\x18\n \x01(\r\x12\x13\n\x0bweapon_kill\x18\x0b \x01(\r\"P\n\x17WeaponPowerTitleRecords\x12\x35\n\x07records\x18\x01 \x03(\x0b\x32$.freefire.WeaponPowerTitleRecordInfo\"\xcd\x01\n%CSGetAccountWeaponPowerTitleRecordRes\x12\x32\n\x07records\x18\x01 \x01(\x0b\x32!.freefire.WeaponPowerTitleRecords\x12\x35\n\x14weapon_exp_info_list\x18\x02 \x03(\x0b\x32\x17.freefire.WeaponExpInfo\x12\x39\n\x16weapon_award_info_list\x18\x04 \x03(\x0b\x32\x19.freefire.WeaponAwardInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WeaponPower_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSGETACCOUNTWEAPONPOWERTITLERECORDREQ']._serialized_start=75
  _globals['_CSGETACCOUNTWEAPONPOWERTITLERECORDREQ']._serialized_end=134
  _globals['_WEAPONPOWERTITLERECORDINFO']._serialized_start=137
  _globals['_WEAPONPOWERTITLERECORDINFO']._serialized_end=435
  _globals['_WEAPONPOWERTITLERECORDS']._serialized_start=437
  _globals['_WEAPONPOWERTITLERECORDS']._serialized_end=517
  _globals['_CSGETACCOUNTWEAPONPOWERTITLERECORDRES']._serialized_start=520
  _globals['_CSGETACCOUNTWEAPONPOWERTITLERECORDRES']._serialized_end=725
# @@protoc_insertion_point(module_scope)
