# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WeaponExp.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'WeaponExp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fWeaponExp.proto\x12\x08\x66reefire\"2\n\x1c\x43SGetAccountWeaponExpInfoReq\x12\x12\n\naccount_id\x18\x01 \x01(\x04\"\x92\x01\n\rWeaponExpInfo\x12\x11\n\tweapon_id\x18\x01 \x01(\r\x12\x0b\n\x03\x65xp\x18\x02 \x01(\r\x12\x0c\n\x04kill\x18\x03 \x01(\r\x12\x0e\n\x06\x64\x61mage\x18\x04 \x01(\r\x12\x10\n\x08headshot\x18\x05 \x01(\r\x12\x0c\n\x04\x63ure\x18\x06 \x01(\r\x12\x10\n\x08use_time\x18\x07 \x01(\r\x12\x11\n\tquad_kill\x18\x08 \x01(\r\"D\n\x0fWeaponAwardInfo\x12\x11\n\tweapon_id\x18\x01 \x01(\r\x12\x1e\n\x12\x61warded_level_list\x18\x02 \x03(\rB\x02\x10\x01\"8\n\rWeaponExpRank\x12\x11\n\tweapon_id\x18\x01 \x01(\r\x12\x14\n\x0crank_percent\x18\x02 \x01(\r\"\xe3\x01\n\x1c\x43SGetAccountWeaponExpInfoRes\x12\x35\n\x14weapon_exp_info_list\x18\x01 \x03(\x0b\x32\x17.freefire.WeaponExpInfo\x12\x39\n\x16weapon_award_info_list\x18\x02 \x03(\x0b\x32\x19.freefire.WeaponAwardInfo\x12\x1a\n\x0epinned_weapons\x18\x03 \x03(\rB\x02\x10\x01\x12\x35\n\x14weapon_exp_rank_list\x18\x04 \x03(\x0b\x32\x17.freefire.WeaponExpRankb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WeaponExp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEAPONAWARDINFO'].fields_by_name['awarded_level_list']._loaded_options = None
  _globals['_WEAPONAWARDINFO'].fields_by_name['awarded_level_list']._serialized_options = b'\020\001'
  _globals['_CSGETACCOUNTWEAPONEXPINFORES'].fields_by_name['pinned_weapons']._loaded_options = None
  _globals['_CSGETACCOUNTWEAPONEXPINFORES'].fields_by_name['pinned_weapons']._serialized_options = b'\020\001'
  _globals['_CSGETACCOUNTWEAPONEXPINFOREQ']._serialized_start=29
  _globals['_CSGETACCOUNTWEAPONEXPINFOREQ']._serialized_end=79
  _globals['_WEAPONEXPINFO']._serialized_start=82
  _globals['_WEAPONEXPINFO']._serialized_end=228
  _globals['_WEAPONAWARDINFO']._serialized_start=230
  _globals['_WEAPONAWARDINFO']._serialized_end=298
  _globals['_WEAPONEXPRANK']._serialized_start=300
  _globals['_WEAPONEXPRANK']._serialized_end=356
  _globals['_CSGETACCOUNTWEAPONEXPINFORES']._serialized_start=359
  _globals['_CSGETACCOUNTWEAPONEXPINFORES']._serialized_end=586
# @@protoc_insertion_point(module_scope)
