# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Wishlist.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'Wishlist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eWishlist.proto\x12\x11\x66reefire.wishlist\"+\n\x15\x43SGetWishListItemsReq\x12\x12\n\naccount_id\x18\x01 \x01(\x04\"5\n\x0cWishItemInfo\x12\x0f\n\x07item_id\x18\x01 \x01(\r\x12\x14\n\x0crelease_time\x18\x02 \x01(\x04\"G\n\x15\x43SGetWishListItemsRes\x12.\n\x05items\x18\x01 \x03(\x0b\x32\x1f.freefire.wishlist.WishItemInfo\"N\n\x19\x43SWishListLeaderboardItem\x12\x0f\n\x07item_id\x18\x01 \x01(\r\x12\x12\n\nchange_cnt\x18\x02 \x01(\r\x12\x0c\n\x04rank\x18\x03 \x01(\r\"\x9c\x01\n\x1b\x43SGetWishListLeaderboardRes\x12=\n\x07item_7d\x18\x01 \x03(\x0b\x32,.freefire.wishlist.CSWishListLeaderboardItem\x12>\n\x08item_30d\x18\x02 \x03(\x0b\x32,.freefire.wishlist.CSWishListLeaderboardItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Wishlist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CSGETWISHLISTITEMSREQ']._serialized_start=37
  _globals['_CSGETWISHLISTITEMSREQ']._serialized_end=80
  _globals['_WISHITEMINFO']._serialized_start=82
  _globals['_WISHITEMINFO']._serialized_end=135
  _globals['_CSGETWISHLISTITEMSRES']._serialized_start=137
  _globals['_CSGETWISHLISTITEMSRES']._serialized_end=208
  _globals['_CSWISHLISTLEADERBOARDITEM']._serialized_start=210
  _globals['_CSWISHLISTLEADERBOARDITEM']._serialized_end=288
  _globals['_CSGETWISHLISTLEADERBOARDRES']._serialized_start=291
  _globals['_CSGETWISHLISTLEADERBOARDRES']._serialized_end=447
# @@protoc_insertion_point(module_scope)
